baseURL = 'https://gp.berviantoleo.my.id/blog/'
languageCode = 'en-us'
title = "Leo's Blog"
author = "Bervianto Leo Pratama"
DefaultContentLanguage = "en-us"
enableInlineShortcodes = true
canonifyURLs = true
relativeURLs = false

[params]
  env = "production"
  googleAnalytics = "G-TKL9K49MPQ"  # Replace with your GA4 ID

  twitter = 'berviantoleo'
  github = 'berviantoleo'
  instagram = 'bervianto.leo'

  avatar = 'bervianto.leo@gmail.com'
  name = 'Bervianto Leo Pratama'
  bio = 'Software Engineer'

[pagination]
  pagerSize = 7

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  defaultMarkdownHandler = 'goldmark'

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
